name: Build and Publish Python Package to PyPI

on:
  release:
    types: [ published ]

jobs:
  publish-python-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Publish to PyPI
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          package_directory: "src"
